services:
  bot:
    build: .
    container_name: goldbot

    restart: unless-stopped

    env_file: .env

    sysctls:
      net.ipv6.conf.all.disable_ipv6: "1"

    volumes:
      - goldbot-data:/data

    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  goldbot-data:
